apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    label:
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://prometheus:9090
    editable: false
    jsonData:
      httpMethod: POST