# docker compose file named according to the preferred documentation ( https://docs.docker.com/compose/compose-file/#compose-file )
services:
  grafana:
    ports:
      - "3000:3000"
    image: grafana/grafana-oss
    volumes:
      - type: bind
        # use either of the supplied .ini files for different scenarios
        source: ./grafana/grafana-generic-google-oauth-rolemapping.ini
        # default config file locations can be found here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#default-paths
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ./grafana/data-sources
        target: /etc/grafana/provisioning/datasources
      - type: bind
        source: ./grafana/dashboards-config
        target: /etc/grafana/provisioning/dashboards
      - type: bind
        source: ./grafana/dashboards
        target: /etc/grafana-dashboards
  prometheus:
    ports:
      - "9090:9090"
    image: prom/prometheus
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/prometheus/sa.json
    volumes:
      - type: bind
        # use either of the supplied .ini files for different scenarios
        source: ./prometheus/config.yml
        # default config file locations can be found here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#default-paths
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./prometheus/sa.json
        target: /etc/prometheus/sa.json
