source/link:https://mjpitz.com/blog/2020/10/21/local-ingress-domains-kind[mjpitz blog]

== Configuring KIND and Kubernetes Ingress with locally running domain
artpav <artemijs.pavlovs@unblu.com> +
2021.3, 2021-03-19

=== We will need

[source,bash]
----
# docker : https://www.docker.com/get-started
brew install docker

# kind ( kubernetes in docker ) itself: https://kind.sigs.k8s.io/docs/user/quick-start/
brew install kind

# dnsmasq for local Domain : https://wiki.archlinux.org/index.php/dnsmasq 
brew install dnsmasq
----

=== Configuring local domain using dnsmasq

Source : link:https://mjpitz.com/blog/2020/10/21/local-ingress-domains-kind/[MJPitz Blog Post]


- add desired local domain mapping and DNS servers to dnsmasq config

[source,bash]
----
# /usr/local/etc/dnsmasq.conf

address=/YOUR.DOMAIN/127.0.0.1
server=8.8.8.8
server=8.8.4.4
----

- restart dnsmasq service

[source,bash]
----
sudo brew services restart dnsmasq
----

- Configure a DNS resolver to point to localhost address

[source,bash]
----
sudo mkdir /etc/resolver/

cat <<EOF | sudo tee /etc/resolver/YOUR.DOMAIN
domain YOUR.DOMAIN
search YOUR.DOMAIN
nameserver 127.0.0.1
EOF
----

- Restart ``mDNSResponder`` process

[source,bash]
----
sudo killall -HUP mDNSResponder
----

- add localhost IP ( 127.0.0.1 ) to your DNS network settings


=== Creating and configuring KIND

[source,bash]
----
kind create cluster --config ./kind-config.yml
----

here's a basic kind cluster configuration, more @ +
link:https://kind.sigs.k8s.io/docs/user/configuration[KIND documentation] +
and in link:kind-config.yml[Local Config File]

[source,yaml]
----
# kind-config.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: artpav-dev-local
nodes:
  - role: control-plane
    # image: kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55 # custom kubernetes version
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: 127.0.0.1
      - containerPort: 443
        hostPort: 443
        listenAddress: 127.0.0.1
----


=== Deploying NGINX Ingress controller

Source : link:https://kind.sigs.k8s.io/docs/user/ingress#ingress-nginx[KIND docs : ingress-nginx]

[%hardbreaks]
deploy nginx ingress with kind specific patches
[source,bash]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
----

wait for ingress controller pod to become available

[source,bash]
----
kubectl wait --namespace ingress-nginx \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/component=controller \
  --timeout=90s
----

=== Testing

[source,yaml]
----
# test-app.yml
---
kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  labels:
    app: foo
spec:
  containers:
  - name: foo-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=foo"
---
kind: Pod
apiVersion: v1
metadata:
  name: bar-app
  labels:
    app: bar
spec:
  containers:
  - name: bar-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=bar"
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
  # Default port used by the image
  - port: 5678
---
kind: Service
apiVersion: v1
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  ports:
  # Default port used by the image
  - port: 5678
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: foo.YOUR.DOMAIN
spec:
  rules:
  - host: foo.YOUR.DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: foo-service
          servicePort: 5678
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bar.YOUR.DOMAIN
spec:
  rules:
  - host: bar.YOUR.DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: bar-service
          servicePort: 5678
----

==== Manual

[source,bash]
----
# deploy the app
kubectl apply -f test-app.yml

# check that everything was deployed sucesfully
# wait for everything to become ready
kubectl get all,ingress

# check domain availability
curl foo.YOUR.DOMAIN
curl bar.YOUR.DOMAIN
----

==== Terratest

[source,bash]
----
go test ./app_test.go -v -timeout 30m -json
----